### ISSUE TITLE
Qgis 3 compatibility

### ISSUE THREAD

**Issue by falcesimo** [3nids/quickfinder#66]
Hello kind developer,
can you create the compatibility for Qgis 3 of Quickfinder plugin?
Best regards and Thank you!!!

**Comment by gilleschapron** [comment]
Hi,

I am very interested by an update to. I use quick finder to index columns of shape file, and I have found no alternative.
I tried to make some change by downloading and editing your sources, but that is not that easy to understand code from someone else. I presume there is some diffulties because of adress search on osm I'am not using. Maybe could be simple to split the functionnalities ?

Many thanks for any answer.

**Comment by 3nids** [comment]
Hi, there is no porting planned, since all its features are now ported:
* indexed search: you can use inbuilt locator filter.
  1. select your layer
  2. type `f what_you_are_searching`
  3. should find the features
* osm: see nominatime plugin
* geomapfish: see Geomapfish Locator plugin

There is also the discovery plugin which is very interesting (search in postgres DB)

**Comment by lennoo** [comment]
I have ported it to QGIS 3, see https://github.com/lennoo/qfinder
